version: '3.8'

# Defining the network for our containers
networks:
  videogamesnet:

# Defining the volumes
volumes:
  mongovideogamesdb:

# Defining the services
services:

  # container PHP
  videogamesphp:
    container_name: phpvideo
    build: 
      context: ./php
    ports: 
      - '9000:9000'
    environment:
      TZ: UTC
      APP_PATH: "/var/www/symfo"
    volumes:
      - ./app:/var/www/symfo
    depends_on:
      - videogamesmongo
    networks:
      - videogamesnet


  # container WEB server
  videogamesnginx:
    container_name: nginxvideo
    image: nginx:stable-alpine
    ports: 
      - '80:80'
      - '443:443'
    volumes:
      - ./app:/var/www/symfo
      # search and syncronize the default.conf file with the nginx container instead of host
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # logs for nginx container will be stored here instead of the host
      - ./logs:/var/log/nginx
    environment:
      TZ: UTC
    depends_on:
      - videogamesphp
      - videogamesmongo
      - videogamesnode
    networks:
      - videogamesnet


  # container nodeJS
  videogamesnode:
    container_name: nodevideo
    build: 
      context: ./node
    volumes:
      - ./app:/var/www/symfo
    environment:
      TZ: UTC
    depends_on:
      - videogamesphp
    networks:
      - videogamesnet
    tty: true
  
  # container no sql mongo
  videogamesmongo:
    container_name: mongovideo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongovideogamesdb:/data/db
      - ./datascript:/datascript
    environment:
      TZ: UTC
      MONGODB_INITDB_ROOT_USERNAME: videoadmin
      MONGODB_INITDB_ROOT_PASSWORD: video2024
    networks:
      - videogamesnet